ARG frontend_image_name
FROM $frontend_image_name as first_image
FROM node:11.12-alpine

RUN yarn global add local-web-server
RUN mkdir /app
COPY --from=first_image /app/dist /app/dist
CMD ["ws", "--spa", "/dist/index.html", "--rewrite", "'/* -> /dist/$1'"]
